sudo: required
dist: xenial
install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports main
  restricted universe'
- sudo apt-get update
- sudo apt-get install -y shellcheck
- gem install rubocop goodcop
script:
- find . -executable -type f ! -path './.git/*' | xargs shellcheck -e SC1071
- rubocop -D
notifications:
  email: false
  slack:
    secure: qn1/sSFabGwei6Li2k8yxIx2ZI7mIVVovz4nSKsCta+suyPhZe4kuw178L1IFu2Xvnxnq63uAiZ2VxeNN5Z0DkI1e/pN8hfubo51fQW9nbb6zubEjdOj3G0fDhszB0R8nbPqAFdml2CqYqmokIF4aIhbRkjYxtYk+5WnnInbLLFWqLUjue8XZRUbXrM3+oDhi2EPwsSvBdhfkhiZlXJXifA3pwSfidzcn/x2d4tcgpMecU2dSTI1HLVgEx6RsffkXMtJRaD+VSs3+BpYJjX4Hn7h8MNlfkxba6cwMaxrib9F+cxlai/upwSvRqqV1dh6Vd49M/SusfumvV0w1SZEcDnWrrZgrbVujnu0lH/oi3PFQ00vCo80CVBb20y3RC6dWL9aytefjiRmSkpX8OySeCzdux10FXICq6ZPTqIHoy8vgg88/paG7Otze7Yq4FYwPw3nd5658pat75OaEeKoHVSDnuHtdqtc7vegDrg30E+Fb/aA6K90AXB9+95Tdjbz6l0jY9pfTQKaBvw202RTjnEYRNQihbEKsbVQLf7Sme2Sapfrkg2pWmxJh5lEJz9LI7pL0OoT5ziC3Wb20ADJbAgTW73H5wbbiW9t6hejUB/DZ59o6kX8+TCPbAkLCuAz3QEiFdncbejI05WRJJ4Xq7Rn0w9cQZPuTMPI0G3td/U=
