#!/bin/sh
[[ "$PAM_TYPE" == "close_session" ]] && exit
mail -s "Authentication on $(hostname) via $PAM_SERVICE" root <<CONTENTS
Auth type: $PAM_TYPE
Timestamp: $(date)
New user: $PAM_USER
Originating User: $PAM_RUSER
TTY: $PAM_TTY
CONTENTS

