#!/usr/bin/env ruby

require 'yaml'
require 'date'
require 'cymbal'

def add_action(calendar, action, date)
  action[:amount] *= -1 unless action[:type] == 'income'
  calendar[date] << { name: action[:name], amount: action[:amount] }
end

activity_file = ARGV.shift
current_value = (ARGV.shift || 0).to_i
months = (ARGV.shift || 6).to_i

ACTIVITY = Cymbal.symbolize(File.open(activity_file) { |fh| YAML.load fh })

CALENDAR = Hash.new { |h, k| h[k] = [] }

ACTIVITY.each_with_object(CALENDAR) do |action, calendar|
  dates = action[:when]
  dates = [dates] unless dates.is_a? Array
  dates.each { |date| add_action(calendar, action, date) }
end

