#!/usr/bin/env ruby

require 'optparse'

def current_version(cask_name)
  Dir.new("/opt/homebrew-cask/Caskroom/#{cask_name}").to_a.last
end

def latest_version(cask_name)
  `brew cask info #{cask_name}`.split[1]
end

def upgrade(cask)
  puts "Upgrading #{cask.name} from #{cask.current} to #{cask.latest}"
  system 'brew', 'cask', 'uninstall', '--force', cask.name
  system 'brew', 'cask', 'install', cask.name
end

def noop(cask)
  puts "Would upgrade #{cask.name} from #{cask.current} to #{cask.latest}"
end

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: cask_upgrade [-n|--noop] [cask_name]'
  opts.on('-n', '--noop', 'Do not perform upgrade(s)') do
    options[:noop] = true
  end
end.parse!

cask_names = ARGV || `brew cask list -1`.split

Cask = Struct.new :name, :current, :latest

Casks = cask_names.map do |cask_name|
  Cask.new(
    cask_name,
    current_version(cask_name),
    latest_version(cask_name)
  )
end

puts "Found #{Casks.size} casks"

Casks.each do |cask|
  if cask.latest == 'latest' || cask.current != cask.latest
    options[:noop] ? noop(cask) : upgrade(cask)
  end
end
