#!/usr/bin/env ruby

require 'prospectus'
require 'digest'
require 'open-uri'

def load_deps
  Prospectus.load(all: true).map do |x|
    next nil unless x.name =~ /::/
    next nil if x.name =~ /circleci/
    [x.name.split('::').last, x.expected]
  end.compact
end

def load_checksum(dep, version)
  url = 'https://github.com/amylum/' \
        "#{dep}/releases/download/#{version}/#{dep}.tar.gz"
  Digest::SHA256.hexdigest open(url).read
end

def load_dep_text(deps)
  deps.map do |name, version|
    sum = load_checksum(name, version)
    sname = name.include?('-') ? "'#{name}'" : name
    "  #{sname}: {\n    version: '#{version}',\n    checksum: '#{sum}'\n  }"
  end.join(",\n")
end

def update_file!(text)
  new = File.read('.pkgforge').sub(/^deps\($[^)]+^\)$/m, "deps(\n#{text}\n)")
  File.open('.pkgforge', 'w') { |fh| fh << new }
end

deps = load_deps
text = load_dep_text(deps)
update_file!(text)
