#!/usr/bin/env bash

# curl -sL https://git.io/vbDoO | bash

set -euo pipefail

apt update
apt upgrade -y
apt install software-properties-common
apt-add-repository ppa:ansible/ansible
apt update
apt install ansible python-pip
pip install virtualenv
pip install --upgrade pip
git clone https://github.com/trailofbits/algo /opt/algo
cd /opt/algo
python -m virtualenv env
source env/bin/activate
python -m pip install -U pip
python -m pip install -r requirements.txt
./algo

