#!/usr/bin/env bash

# curl -sL https://git.io/vbDoO | bash

set -euo pipefail

apt update
apt upgrade -y
apt install -y software-properties-common
apt-add-repository -y ppa:ansible/ansible
apt update
apt install -y ansible python-pip git
pip install virtualenv
pip install --upgrade pip
git clone https://github.com/trailofbits/algo /opt/algo
cd /opt/algo
python -m virtualenv env
source env/bin/activate
pip install -r requirements.txt
./algo

