#!/usr/bin/env bash

# curl -sL https://git.io/vbDoO | bash

set -euo pipefail

apt update
apt upgrade -y
apt install -y ansible python-pip build-essential python-dev

pip install --upgrade pip
pip install virtualenv

git clone https://github.com/trailofbits/algo /opt/algo
(
    cd /opt/algo

    python -m virtualenv env
    source env/bin/activate
    pip install -r requirements.txt

    ansible-playbook \
        deploy.yml \
        -t local,vpn,ssh_tunneling \
        -e "server_ip=localhost
            server_user=root
            IP_subject_alt_name=96.126.120.115
            OnDemandEnabled_Cellular=Y
            OnDemandEnabled_WIFI=Y
            OnDemandEnabled_WIFI_EXCLUDE='_null'" \
        --skip-tags _null,encrypted,cloud,update-alternatives
)

