#!/usr/bin/env zsh

if [ -z "$1" ] ; then
    echo 'Usage: gem_sync <old_ruby_version>'
    exit 1
fi

OLD="$1"
NEW="$(rbenv global)"

GEMFILE="$(mktemp)"
echo "source 'https://rubygems.org'" > $GEMFILE

rbenv shell $1
gem list --no-versions --no-verbose | sed 's/\(.*\)/gem "\1"/' >> $GEMFILE
rbenv shell --unset

gem install bundler
bundle install --gemfile=$GEMFILE

