#!/usr/bin/env ruby

OLD_VERSION = ARGV.first

raise("Usage: #{__FILE__} <old-version>") unless OLD_VERSION

unless `rbenv versions --bare`.split.include? OLD_VERSION
  raise "Ruby version not found: #{OLD_VERSION}"
end

cmd = `RBENV_VERSION=#{OLD_VERSION} rbenv exec gem list`
gems = cmd.lines.map { |x| x.gsub(/[\n(),]/, '').split }

def installed?(gem, version)
  system "gem list -i #{gem} -v #{version} >/dev/null 2>/dev/null"
end

gems.each do |gem, *versions|
  versions.each do |version|
    next if installed? gem, version
    puts "Installing #{gem} #{version}"
    `gem install #{gem} -v #{version} >/dev/null 2>/dev/null`
    next if installed? gem, version
    puts 'Failed to install!'
  end
end
