#!/usr/bin/env ruby

require 'octoauth'
require 'octokit'

title = ARGV.shift
body = ARGV.shift
fail('no title provided') unless title

remote_info = `git remote show origin -n`.lines
remote = remote_info.find { |x| x.match('Fetch URL') }.split.last
fail('origin is not a github repo') unless remote.match('github.com')
repo = remote.gsub(/.*github\.com[:\/]/, '').gsub('.git', '')

auth = Octoauth.new(
  note: 'issues',
  file: :default,
  autosave: true,
  scopes: ['repo', 'public_repo']
)
client = Octokit::Client.new access_token: auth.token, auto_paginate: true

issue = client.create_issue(repo, title, body)
puts issue[:html_url]
