#!/bin/bash

if [ -z "$1" ] ; then
  SOURCEDIR="$(pwd)"
else
  SOURCEDIR="$1"
fi

if [ -z "$2" ] ; then
  DESTFILE="$HOME/.ssh/authorized_keys"
else
  DESTFILE="$2"
fi

if [ -z "$3" ] ; then
  echo -e "Updating '$DESTFILE' from keys in '$SOURCEDIR'\nPress enter to confirm"
  read
fi

[ -f $DESTFILE ] && mv $DESTFILE $DESTFILE.save

for file in $(ls $SOURCEDIR/*.pub) ; do
  cat ${file} >> $DESTFILE
done
echo -e "\n" >> $DESTFILE

