#!/usr/bin/env bash

basedir="${HOME}/.gpg-agent.d"
mkdir -p $basedir

homedir="${1}"
: ${homedir:=$GNUPGHOME}
: ${homedir:=~/.gnupg}
agentfile="${basedir}/${homedir//\//.}"

[ -f "${agentfile}" ] && . $agentfile

oldpid=$(echo $GPG_AGENT_INFO | cut -d: -f2)
matchstring="${oldpid}.*[g]pg-agent.*${agentfile}"

if [ -z "$oldpid" -o -z "$(ps aux | grep "$matchstring")" ] ; then
    touch $agentfile
    chmod 600 $agentfile
    /usr/bin/env gpg-agent --homedir $homedir --daemon --write-env-file $agentfile
fi

echo $agentfile

