#!/usr/bin/env bash

# Original code from http://www.slackwiki.com/Dependency_Discovery
# Modified to handle pacman ownership checking

ECHO=/usr/bin/echo
SED=/usr/bin/sed
FILE=/usr/bin/file
CUT=/usr/bin/cut
LDD=/usr/bin/ldd
GREP=/usr/bin/grep
PACMAN=/usr/bin/pacman

for p in `$ECHO $PATH | $SED 's/:/ /g'` ;do
    for f in $p/* ; do
        if [ 'ELF' == `$FILE -b $f | $CUT -d' ' -f1` ]; then
            if $LDD $f | $GREP -q 'not found'; then
                $ECHO -n "$($PACMAN -Qoq $f) "
                $ECHO -n "$f "
                $ECHO -n $($LDD $f | $GREP 'not found' | $CUT -d' ' -f1)
                $ECHO
            fi
        fi
    done
done | sort

