#!/usr/bin/env bash

date="$(date --date='23:59:59 yesterday')"
author="$(git config user.name)"
for i in $(find . -name .git) ; do #shellcheck disable=SC2044
    count="$(git --git-dir="$i" log \
        --after="$date" \
        --author="$author" \
        --pretty=oneline \
        | wc -l)"
    if [[ "$count" -ne "0" ]] ; then
        repo="$(dirname "$i")"
        echo "$repo $count"
    fi
done
