#!/usr/bin/env bash

set -e

nftables_start() {
    find /etc/nftables -type f -name '*.rules' -executable | sort | xargs --no-run-if-empty -n1 nft -f
}

nftables_stop() {
    for protocol in ip ip6 arp bridge ; do
        for table in $(nft list tables $protocol | cut -d ' ' -f 2) ; do
            nft flush table $protocol $table
            for action in flush delete ; do
                nft list table $protocol $table | awk '/^[ \t]+chain/{ print $2 }' | xargs -r -L 1 nft $action chain $protocol $table
                nft list sets $protocol $table | awk '/^[ \t]+set/{ print $2 }' | xargs -r -L 1 nft $action set $protocol $table
            done
            nft delete table $protocol $table
        done
    done
}

case $1 in
    start)
        nftables_start
        ;;
    stop)
        nftables-stop
        ;;
    *)
        echo "Usage: $0 start|stop|restart|list"
        exit 1
        ;;
esac

