#!/usr/bin/env bash

function needful () {
    local repo="$(dirname $1)"
    (
        cd $repo
        local current="$(git rev-parse --abbrev-ref HEAD)"
        local desired="$(git config reposync.branch || echo "master")" 
        [ "$current" == "$desired" ] || git checkout "$desired" &> /dev/null
        git fetch --tags &> /dev/null
        git pull origin "$desired" &> /dev/null \
            || echo "Error! Failed to pull $repo"
        git submodule update --init &> /dev/null \
            || echo "Error! Failed to update submodules for $repo"
        [ "$current" == "$desired" ] || git checkout "$current" &> /dev/null
    )
}
export -f needful


if [ -n "$SLOW_SSH" ] ; then
    PARALLEL=1
else
    PARALLEL=10
fi

# Make sure SSH key is loaded before kicking off workers
ssh git@github.com &>/dev/null

find . -type d -name '.git' | xargs -n1 -P$PARALLEL -I{} bash -c "needful {}"
