#!/usr/bin/env bash

if [ -z "$1" ] ; then
    action='pull'
else
    action="$1"
fi

function needful () {
    local action="$1"
    local repo="$(dirname $2)"
    (
        cd $repo
        current="$(git branch | awk '/^\*/ { print $2}')"
        [ "$current" == "master" ] || git checkout master &> /dev/null
        git fetch --tags &> /dev/null
        git $action origin master &> /dev/null \
            || echo "Error! Failed to pull $repo"
        [ "$current" == "master" ] || git checkout $currentBranch &> /dev/null
    )
}
export -f needful


if [ -n "$SLOW_SSH" ] ; then
    PARALLEL=1
else
    PARALLEL=10
fi

find . -type d -name '.git' | xargs -n1 -P$PARALLEL -I{} bash -c "needful $action {}"
