#!/usr/bin/env bash

if [ -z "$1" ] ; then
    action='pull'
else
    action="$1"
fi

if [ -z "$2" ] ; then
    repoPath="$(pwd)"
else
    repoPath="$2"
fi

for gitDir in $(find $repoPath -type d -name '.git') ; do 
    repo="$(dirname $gitDir)"
    (
        cd $repo
        current="$(git branch | awk '/^\*/ { print $2}')"
        [ "$current" == "master" ] || git checkout master &> /dev/null
        git $action origin master &> /dev/null \
            || echo "Error! Failed to pull $repo"
        [ "$current" == "master" ] || git checkout $currentBranch &> /dev/null
    )
done

