#!/usr/bin/env bash

set -euo pipefail

uuid="$(uuidgen)"
basepath="s3://${SCRATCH_BUCKET}/${uuid}/"

for src in "$@" ; do
    aws s3 cp --only-show-errors "$src" "$basepath"
    dstname="$(basename "$src")"
    echo "${SCRATCH_HOSTNAME}/${uuid}/${dstname}"
done
