#!/usr/bin/env bash

set -euo pipefail

: ${SCRATCH_BUCKET:=akerl-scratch}
: ${SCRATCH_HOSTNAME:=https://scratch.scrtybybscrty.org}

uuid="$(uuidgen)"
basepath="s3://${SCRATCH_BUCKET}/${uuid}/"

for src in "$@" ; do
    aws s3 cp --only-show-errors "$src" "$basepath"
    dstname="$(basename "$src")"
    echo "${SCRATCH_HOSTNAME}/${uuid}/${dstname}"
done
