#!/usr/bin/env bash

if [ -z "$1" ] ; then
  repoPath="$(pwd)"
else
  repoPath="$1"
fi

for file in /usr/local/bin/* ; do
  if [ -L "$file" ] ; then
    if [ ! -e "$(readlink $file)" ] ; then
      rm $file
    fi
  fi
done

for file in $repoPath/*  ; do
  [[ -x $file ]] || continue
  name=${file##*/}
  if [ ! -e "/usr/local/bin/$name" ] ; then
    ln -s $file /usr/local/bin/$name
  fi 
done

