#!/usr/bin/env ruby

require 'parallel'
require 'mercenary'
require 'prospectus'

##
# Runner class to check prospectuses
class Runner
  def initialize(params)
    @program_name = $PROGRAM_NAME
    @options = params
    @options[:dir] ||= File.expand_path('~/src')
    @options[:maxdepth] ||= 2
  end

  def run!
    params = @options[:serial] ? { in_processes: 1 } : {}
    results = Parallel.map(all_dirs, params) { |x| [x, worker(x)] }
    print_results(results)
    cache_failures(results)
  end

  private

  def print_results(results)
    results.each do |dir, list|
      next if list == [false]
      prefix = dir.split('/')[-2]
      list.each { |x| puts "#{prefix}:#{x.name}: #{x.actual} / #{x.expected}" }
    end
  end

  def prospectus_options
    @prospectus_options ||= {
      all: @options[:all],
      good_only: @options[:good_only]
    }
  end

  def cache_file
    @cache_file ||= File.join(@options[:dir], '.allprop')
  end

  def all_files
    @all_files ||= Dir.glob(
      @options[:dir] + '/*' * @options[:maxdepth] + '/.prospectus*'
    )
  end

  def load_cache
    return nil unless @options[:cache] && File.exist?(cache_file)
    File.read(cache_file).split "\n"
  end

  def all_dirs
    @all_dirs ||= load_cache
    @all_dirs ||= all_files.map { |x| File.dirname(x) }.sort.reverse
  end

  def worker(dir)
    $PROGRAM_NAME = "#{@program_name} thread #{dir}"
    Dir.chdir(dir) { Prospectus.load(prospectus_options) }
  rescue Exception # rubocop:disable Lint/RescueException
    puts "Failed to load #{dir}"
    [false]
  end

  def cache_failures(results)
    failures = results.reject { |_, list| list.empty? }.map(&:first)
    File.open(cache_file, 'w') { |fh| fh << failures.join("\n") }
  end
end

Mercenary.program(:allprop) do |p|
  p.description 'Run prospectus against all subdirs'
  p.syntax 'allprop [options]'

  # rubocop:disable Metrics/LineLength
  p.option :cache, '-c', '--cache', 'Use cache to check only fails from last time'
  p.option :dir, '-d DIR', '--dir', 'Root dir (defaults to ~/src)'
  p.option :maxdepth, '-m DEPTH', '--maxdepth', 'Max depth to search'
  p.option :all, '-a', '--all', 'Show all items'
  p.option :good_only, '-g', '--good', 'Show only items with good state'
  p.option :serial, '-s', '--serial', 'Do not parallelize execution'
  # rubocop:enable Metrics/LineLength

  p.action do |_, options|
    Runner.new(options).run!
  end
end
