#!/usr/bin/env bash

if [[ -z "$1" ]] ; then
    echo "Please specify a host"
    exit 1
fi

if ssh -oConnectTimeout=2 "$1" true &>/dev/null ; then
    echo "Connection available"
    exit
else
    echo "I cannot connect"
    exit 1
fi

