#!/usr/bin/env bash

# The MIT License (MIT)
# 
# Copyright (c) 2016 Les Aker
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Opens the Gemnasium page for a repo/branch in your browser.

if [ ! -e README.md ] ; then
  echo "No README.md found to parse Gemnasium link"
  exit 1
fi

URL="$(grep '^\[!\[Dependency Status\].*)](https://gemnasium.com/.*)' README.md | sed 's/.*)](//;s/)//')"

if [ -z "$URL" ] ; then
  echo "Failed to parse URL from README.md"
  exit 1
fi

open "$URL"
