#!/usr/bin/env ruby

unless File.exist?('README.md') && File.read('README.md').match(/^Quotes/)
  puts 'You should run this from the quotes directory'
  exit
end

Signal.trap('INT') { exit }

files = Dir.glob('**/*').select do |x|
  File.file?(x) && x !~ /\.yml|\.md/ && x !~ /^scripts/
end
quotes = files.map { |x| File.readlines(x) }.flatten.map(&:rstrip).shuffle

quotes.each do |x|
  system 'clear'
  puts x
  gets
end
