#!/usr/bin/env bash

set -e

function needful () {
    local repo
    repo="$(dirname "$1")"
    (
        cd "$repo"
        local current
        local desired
        current="$(git rev-parse --abbrev-ref HEAD)"
        desired="$(git config reposync.branch || echo "master")" 
        [ "$current" == "$desired" ] || git checkout "$desired" &> /dev/null
        git fetch --tags &> /dev/null
        git pull origin "$desired" &> /dev/null \
            || echo "Error! Failed to pull $repo"
        git submodule update --init &> /dev/null \
            || echo "Error! Failed to update submodules for $repo"
        [ "$current" == "$desired" ] || git checkout "$current" &> /dev/null
    )
}
export -f needful


if [ -n "$REPO_SYNC_WORKERS" ] ; then
    PARALLEL="$REPO_SYNC_WORKERS"
elif [ -n "$SLOW_SSH" ] ; then
    PARALLEL=1
else
    PARALLEL=10
fi

# Make sure SSH key is loaded before kicking off workers
ssh git@github.com &>/dev/null || true

find . -type d -name '.git' ! -path '*/.gopath/*' -print0 | xargs -0 -n1 "-P$PARALLEL" -I{} bash -c "needful {}"
