#!/usr/bin/env ruby

require 'prospectus'
require 'userinput'

def preflight
  raise('No pkgforge found') unless File.exist? '.pkgforge'
end

def load_version
  state = Prospectus.load(all: true).find { |x| x.name !~ /::/ }
  raise('No version info found') unless state
  state.expected.value
end

def load_revision(version)
  tags = `git tag`.split("\n")
  this_version = tags.select { |x| x =~ /^#{Regexp.escape(version)}-/ }
  (this_version.map { |x| x.split('-').last.to_i }.max || 0) + 1
end

def confirm
  print 'Does this look correct? [Y/n] '
  exit if gets.chomp.casecmp('n').zero?
end

noconfirm = ARGV.shift

preflight
version = load_version
revision = load_revision(version)

tag = "#{version}-#{revision}"
puts "Creating tag #{tag}"
confirm unless noconfirm
system 'git', 'tag', '-m', tag, tag
